version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e  'js,pug,html' index.js
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8081:80"
